---
title: 'Data Analytics: In - Class'
author: "Brendan Donnelly"
date: "September 11, 2020"
output:
  html_document: default
  pdf_document: default
---

# Example Data Frame Practice
```{r eval=F}
days<- c("Mon", "Tues", "Wed", "Thurs", "Fri")
snowed<- c(T,T,F,T,T,T,T)
temperature<- c(10,10,10,10,10,10)
help("data.frame")


empty.DataFrame <-data.frame()
v1<-1:10
v1
letters
v2<-letters[1:10]
df <- data.frame(col.name.1 = v1,col.name.2 = v2)
df

#import/export data
#writing to CSV
write.csv(df,file = "example")

```

# EPI 2010 data
```{r echo= T}
EPI<-read.csv("/Users/donneb/Documents/DataAnalytics/EPI_data.csv")

EPI$EPI #test print of vals

summary(EPI$EPI)   #stats
fivenum(EPI$EPI, na.rm = T)
stem(EPI$EPI)
hist(EPI$EPI, seq(30.,95.,1.0), prob=T, main = "Histogram of EPI")
lines(density(EPI$EPI,na.rm=T,bw=1.))
rug(EPI$EPI)
```

# Exercise 1, Exploratory Analysis 2 Vars EPI
### EPI DALY
```{r daly}
plot(ecdf(EPI$DALY),do.points=F, verticals=T, main = "CDF Daly")
par(pty="s")
#normal dist plot
qqnorm(EPI$DALY);qqline(EPI$DALY)
#boxplot
boxplot(EPI$DALY)
```

### EPI CLIMATE
```{r clim}
#cumulative density plot
plot(ecdf(EPI$CLIMATE),do.points=F, verticals=T, main = "CDF Climate")
par(pty="s")
help("par")
#normal dist plot
qqnorm(EPI$CLIMATE);qqline(EPI$CLIMATE)
#boxplot
boxplot(EPI$CLIMATE)

```

# Excercise 2, Exploratory Analysis 2 Vars GRUMP

## GRUMP RefYearFirst
```{r}
GRUMP<-read.csv("/Users/donneb/Documents/DataAnalytics/GPW3_GRUMP_SummaryInformation_2010.csv")

summary(GRUMP$RefYearFirst)   #stats
fivenum(GRUMP$RefYearFirst, na.rm = T)
stem(GRUMP$RefYearFirst)

#Exercise 2, exploratory analysis 2 vars
### First Years
#cumulative density plot
plot(ecdf(GRUMP$RefYearFirst),do.points=F, verticals=T, main = "CDF RefYearFirst")
par(pty="s")
#normal dist plot
qqnorm(GRUMP$RefYearFirst);qqline(GRUMP$RefYearFirst)
#boxplot
boxplot(GRUMP$RefYearFirst)
```

## GRUMP Populations
```{r pop}
#cumulative density plot
plot(ecdf(GRUMP$PopulationPerUnit),do.points=F, verticals=T, main = "CDF Population")
par(pty="s")
#normal dist plot
qqnorm(GRUMP$PopulationPerUnit);qqline(GRUMP$PopulationPerUnit)
#boxplot
boxplot(GRUMP$PopulationPerUnit)

```
